version: '3.8'
services:
  consul-server1:
    image: consul:1.15.4
    command: agent -server -bootstrap-expect=3 -node=server1 -client=0.0.0.0 -bind=0.0.0.0 -ui
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul-data1:/consul/data

  consul-server2:
    image: consul:1.15.4
    command: agent -server -node=server2 -client=0.0.0.0 -bind=0.0.0.0 -retry-join=consul-server1 -ui
    depends_on:
      - consul-server1
    volumes:
      - consul-data2:/consul/data

  consul-server3:
    image: consul:1.15.4
    command: agent -server -node=server3 -client=0.0.0.0 -bind=0.0.0.0 -retry-join=consul-server1 -ui
    depends_on:
      - consul-server1
    volumes:
      - consul-data3:/consul/data

volumes:
  consul-data1:
  consul-data2:
  consul-data3:
