HOST: 127.0.0.1
PORT: "8080"
USER_SERVICE_HOST: 127.0.0.1
USER_SERVICE_PORT: "50052"
WHITELIST_METHODS_GET_PATH:
  - /users/*
WHITELIST_METHODS_POST_PATH:
  - "/swagger/"
WHITELIST_METHODS_PUT_PATH:
  - "/swagger/"
WHITELIST_METHODS_DELETE_PATH:
  - "/swagger/"