HOST: localhost
PORT: "8080"
USER_SERVICE_HOST: localhost
USER_SERVICE_PORT: "50052"
WHITELIST_METHODS_GET_PATH:
  - /users/*
WHITELIST_METHODS_POST_PATH:
  - "/swagger/"
WHITELIST_METHODS_PUT_PATH:
  - "/swagger/"
WHITELIST_METHODS_DELETE_PATH:
  - "/swagger/"